# A Jekyll template for a simple workshop website, designed for github-pages,
# based on Minima theme https://github.com/jekyll/minima

# Notes:
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Epirus Documentation!
description: "Epirus and the core components"
keywords: "blockchain, epirus, quorum, node"

author: John Chang
pub_year: 2018
github_username: JohnChangUK

# add the full url for the github repository
repo: "https://github.com/JohnChangUK/epirus"

# urls
# your gh-pages url: https://username.github.io
url: https://blk.io
# your repository name: /repository
baseurl: ""

# defaults (to simplify front matter)
defaults:
- scope:
    path: ""
  values:
    layout: default

# Build settings
markdown: kramdown